### ISSUE TITLE
Conflicts with ACF

### ISSUE THREAD

**Issue by tomfinitely** [crowdfavorite/wp-admin-column-view#15]
In WP 3.9, Column View used in conjunction with Advanced Custom Fields replaces ACF's "Custom Fields" dashboard label with "Column View" and causes a 404.

**Comment by scottsweb** [comment]
Also seeing this issue. May need to consider adding a filter to `add_submenu_page()` so certain post types can be ignored.

**Comment by abaney** [comment]
Same issue experienced here also.
