### ISSUE TITLE
Filterable Post Types

### ISSUE THREAD

**Issue by stompweb** [crowdfavorite/wp-admin-column-view#4]
I think adding 'page' by default with a filter to then add extra hierarchical post types might be the best way to go about things.

This would then fix #3 and any other plugin conflicts.

**Comment by alexkingorg** [comment]
I think a filter is a good idea, but will default to "on" for all public CPTs.

**Comment by alexkingorg** [comment]
To double-check, we are only adding to public CPTs

**Comment by stompweb** [comment]
My personal opinion is it's better to have it disabled by default and then enabled explicitly - especially due to wide scope (and often unorthodox) use of post types - ACF for example.

Pages are the perfect use case for this plugin - hence why I think it should be on that by default.

That's my two cents anyway - I'll leave it up to you guys to decide. Cheers for the great plugin.

**Comment by alexkingorg** [comment]
We have a lot of positive feedback from people using it with CMS sites and CPTs.

**Comment by stompweb** [comment]
No, totally I agree it's excellent for any hierarchical data - I was talking with a friend today saying it could/should be an option for core at some point.

I am just being considerate of the amount of use case on none CMS sites and non standard CPTs. 

My thinking is when I'm building a site - I would think "I've got 3 post types that is going to be good for and 2 that it's not useful for, so I'll run those 3 through the filter"

I suppose I'm also thinking of it from a support/compatibility point of view as well - #3 won't be the first plugin this breaks.

**Comment by alexkingorg** [comment]
Fixed in #9
